# Настройки загружаются из config.json
# Настройки Actuator (метрики и здоровье)
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=stub-service
