# Настройки загружаются из config.json
# Настройки Actuator (метрики и здоровье)
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=stub-service

# Настройки логирования
logging.level.org.springframework.web.filter=DEBUG
logging.level.com.example.stub=DEBUG
# Логирование ответов AWS SDK
logging.level.software.amazon.awssdk.services.s3=DEBUG
logging.level.software.amazon.awssdk.request=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
# Путь API
app.api.path=/api/stub

